### ISSUE TITLE
Bower install error

### ISSUE THREAD

**Issue by mmerchel** [backbone-api/facebook#4]
When install the package with bower an error occurred:
- facebook Failed to parse json
  Unexpected token ,
  An error was caught when reading the component.json: Failed to parse json
  Unexpected token ,

**Comment by tracend** [comment]
Thanks @mmerchel for reporting this - haven't installed from bower for a while - should be fixed with the next tag, coming momentarily.

**Comment by mmerchel** [comment]
Thanks for the fast response, that's great.
Please use the new bower package json file bower.json instead of component.json

**Comment by tracend** [comment]
Installed version 0.6.0 successfully using Bower

Closing as addressed
