### ISSUE TITLE
Bower install failing

### ISSUE THREAD

**Issue by trickeyone** [backbone-api/facebook#7]
When I attempt to do a bower install, I'm getting an error on any version that I try it on.

``` shell
bower install backbone.api.facebook
bower not-cached    git://github.com/backbone-api/facebook.git#0.6.0
bower resolve       git://github.com/backbone-api/facebook.git#0.6.0
bower not-cached    git://github.com/backbone-api/facebook.git#*
bower resolve       git://github.com/backbone-api/facebook.git#*
bower download      https://github.com/backbone-api/facebook/archive/0.6.0.tar.gz
bower download      https://github.com/backbone-api/facebook/archive/0.6.0.tar.gz
bower extract       backbone.api.facebook#* archive.tar.gz
bower extract       backbone.api.facebook#0.6.0 archive.tar.gz
bower resolved      git://github.com/backbone-api/facebook.git#0.6.0
bower resolved      git://github.com/backbone-api/facebook.git#0.6.0
bower ENOTFOUND     Package 0 not found
```

Any clues as to what could be causing the error?

Thanks.

**Comment by tracend** [comment]
I can replicate your error but the 0.6.0 version is still available in the repo tags. 

I'd have to speculate that the error may be in the bower registry. 

There was a duplicate entry for this library that was removed months ago but that may have had undesirable side-effects.

**Comment by bekharsky** [comment]
Install fails on my installation too:
alinaki@alinaki-desktop:~/www/fortune/htdocs$ bower install backbone.api.facebook
bower cached        git://github.com/backbone-api/facebook.git#0.6.0
bower validate      0.6.0 against git://github.com/backbone-api/facebook.git#*
bower ENOTFOUND     Package 0 not found

**Comment by agencia** [comment]
check #6 but fix is not available yet on tag

**Comment by tracend** [comment]
True, usually significant feature increments (0.x) are tagged. 

Will upgrade this plugin momentarily.

**Comment by tracend** [comment]
Bower install tested successfully for `backbone.api.facebook@0.7.0`
